openapi : 3.0.1
info :
  title : T-CarShare
  description : Идея по реализации каршеринга
  version : 1.0.0
servers :
  -
    url : 'http://localhost'
paths :
  /car-list :
    get :
      summary : NoName
      description : Метод возвращает список автомобилей
      parameters:
        - $ref: '#/components/parameters/status'
      responses :
        '200' :
          description : Справочник авто
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarList'
        '500':
          description: Системная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiErrorResponse'
              example:
                errorMessage: Произошла системная ошибка
                errorId: '01234567890123456789'
                errorCode: SYSTEM_ERROR
                errorDetails: { }
        
            
  /add-car :
    post :
      summary : Pfdtltybt d cghfdjxybr
      description : Забыли раскладку поменять?
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCar'
      responses :
        '200' :
          description : Успешно добавили новый автомобиль в справочник    
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiSuccssessResponse'
        '500':
          description: Системная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiErrorResponse'
              example:
                errorMessage: Произошла системная ошибка
                errorId: '01234567890123456789'
                errorCode: SYSTEM_ERROR
                errorDetails: { }  
                
  /car-info/{carId} :
    get :
      summary : newMethod2
      description : Сразу видно что у них нет хорошего системного аналитика
      parameters:
        - $ref: '#/components/parameters/carId'

      responses :
        '200' :
          description : OK. Точно ок?
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/carId'
        '500':
          description: Системная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiErrorResponse'
              example:
                errorMessage: Произошла системная ошибка
                errorId: '01234567890123456789'
                errorCode: SYSTEM_ERROR
                errorDetails: { }  

                
  /del-car/{carId} :
      delete:
        summary: summary
        description: description
        parameters:
          - $ref: '#/components/parameters/carId'
        responses :
          '200' :
            description : Успешно добавили новый автомобиль в справочниk
            
          '404':
            description: Ресурс не найден
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UiErrorResponse'
                example:
                  errorMessage: Запрашиваемый ресурс не найден
                  errorId: '01234567890123456789'
                  errorCode: NOT_FOUND
                  errorDetails: { }  
          '500':
            description: Системная ошибка
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UiErrorResponse'
                example:
                  errorMessage: Произошла системная ошибка
                  errorId: '01234567890123456789'
                  errorCode: SYSTEM_ERROR
                  errorDetails: { }     
 
  /driver-licence/new-document : 
      put:
        summary: Без этого вызова - бронить авто нельзя!
        description: Обязательный вызов, потом проверка документа
        requestBody: 
          content:
            multipart/form-data:
              schema: 
                $ref: '#/components/schemas/DriverLisencePhoto'
        
        responses :
          '200' :
            description : Загрузка успешна. Надо проверить на действительность
            content:
              application/json:
                schema:
                 $ref: '#/components/schemas/DownloadDriverLicenceSuccsses'
          '404':
            description: Ресурс не найден
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UiErrorResponse'
                example:
                  errorMessage: Запрашиваемый ресурс не найден
                  errorId: '01234567890123456789'
                  errorCode: NOT_FOUND
                  errorDetails: { }  
          '500':
            description: Системная ошибка
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UiErrorResponse'
                example:
                  errorMessage: Произошла системная ошибка
                  errorId: '01234567890123456789'
                  errorCode: SYSTEM_ERROR
                  errorDetails: { }  
  

components :
  
  parameters :
  
    carId:
      in: path
      name: carId
      description: Идентификатор автомобиля
      required : true 
      schema:
        type: string
        format: uuid
        example: 291a98ff-4eeb-4586-99a2-b19642bbe5ff

    status :
      in : query
      name : status
      description : Статус автомобиля для бронирования клиентом
      required : false
      schema :
        type : string
        enum : [ 'FREE', 'BUSY', 'BROKEN' ]
        example : FREE
  
  schemas :
    
    CarList :
      description: Список автомобилей
      type: array
      items:
        $ref: '#/components/schemas/CarInfo'
        
    CarInfo :
      description: Информация по автомобилю
      type: object
      properties:
        carId:
          description: Уникальный идентификатор автомобиля
          type: string
          format: uuid
          example: 291a98ff-4eeb-4586-99a2-b19642bbe5ff
        status:
          description : Статус автомобиля для бронирования клиентом
          type : string
          enum : [ 'FREE', 'BUSY', 'BROKEN' ]
          example : FREE
        mark:
          description: Марка автомобиля
          type: string
          example: KIA
        model:
          description: Модель автомобиля
          type: string
          example: RIO
        number:
          description: Гос.номер автомобиля
          type: string
          example: А123РН16
        VIN:
          description: VIN-номер автомобиля
          type: string
    
    NewCar:
      title: Добавление нового автомобиля в справочник
      type: object
      properties: 
        mark:
          description: Марка автомобиля
          type: string
          example: KIA
        model:
          description: Модель автомобиля
          type: string
          example: RIO
        number:
          description: Гос.номер автомобиля
          type: string
          example: А123РН16
        VIN:
          description: VIN-номер автомобиля
          type: string 
          example: А123РН16
    
    DriverLisencePhoto:
      title: Скан водительского удостоверения
      type: object
      required: 
        - photo
      properties:
        photo: 
          title: Документ
          type: file
          
    DownloadDriverLicenceSuccsses: 
      title: Succsses
      type: object
      properties:
        docId:
          type: string
          format: uuid
    
    UiErrorResponse :
      title : Информация об ошибке для UI
      allOf :
        -
          $ref : '#/components/schemas/ErrorResponse'
      type : object
      required :
        - success
      properties :
        success :
          title : флаг успешности операции
          type : boolean
          default : false
          
    ErrorResponse :
      title : Информация об ошибке
      required :
        - errorCode
        - errorId
        - errorMessage
        - errorDetails
      type : object
      properties :
        errorMessage :
          title : Сообщение об ошибке
          type : string
          example : Произошла системная ошибка
        errorId :
          title : Идентификатор ошибки
          type : string
          example : '01234567890123456789'
        errorCode :
          title : Код ошибки
          type : string
          example : SYSTEM_ERROR
          
    UiSuccssessResponse:
      description: Айдишник созданного автомобиля
      type: object
      required :
        - carId
      properties :
        carId:
          description: Уникальный идентификатор автомобиля
          type: string
          format: uuid
          example: 291a98ff-4eeb-4586-99a2-b19642bbe5ff
